#!/bin/bash

# Make sure oh-my-zsh is installed
[ ! -d ~/.oh-my-zsh ] && sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Set DOOT_DIR and configType based on environment

if [ -n "$SPIN" ]; then
    DOOT_DIR="$HOME/dotfiles/doots"
    CODE_CONFIG_DIR="$HOME/.config/Code/User"
    CONFIG_TYPE="work"
elif [ "$(uname -m)" = "arm64" ]; then
    DOOT_DIR="$HOME/dev-stuff/dotfiles/doots"
    CODE_CONFIG_DIR="$HOME/Library/Application Support/Code/User"
    CONFIG_TYPE="work"
else
    DOOT_DIR="$HOME/dev-stuff/dotfiles/doots"
    CODE_CONFIG_DIR="$HOME/Library/Application Support/Code/User"
    CONFIG_TYPE="personal"
fi

# Setup Dotfiles
function setupDotfiles() {
  echo "Installing dotfiles for $CONFIG_TYPE..."

  dotfiles=("aliases" "gitconfig" "gitignore_global" "tmux.conf" "vimrc" "zshrc")
  configFiles=("keybindings")

  for dotfile in "${dotfiles[@]}"; do
    if [[ $dotfile == "aliases" || $dotfile == "gitconfig" ]]; then
      source_file="$DOOT_DIR/.$dotfile.$CONFIG_TYPE"
    else
      source_file="$DOOT_DIR/.$dotfile"
    fi

    target_file="$HOME/.$dotfile"
    backup_dir="$HOME/.dotfiles_backup"

    if [[ -f "$target_file" ]]; then
      [[ ! -d "$backup_dir" ]] && mkdir "$backup_dir"
      mv "$target_file" "$backup_dir/$dotfile.bak"
    fi

    echo "Installing $dotfile..."
    cp "$source_file" "$target_file"
  done

  # Configure git to use the global gitignore
  echo "Configuring git to use global gitignore..."
  git config --global core.excludesfile ~/.gitignore_global

  for script in "$HOME/dev-stuff/dotfiles/scripts"/*; do
    echo "Installing $(basename "$script")"
    link="/usr/local/bin/$(basename "$script")"
    if [[ -L "$link" ]]; then
      current_target=$(readlink -f "$link")
      intended_target=$(readlink -f "$script")
      if [[ "$current_target" != "$intended_target" ]]; then
        echo "Updating $link..."
        sudo rm "$link"
        sudo ln -s "$script" "$link"
      else
        current_mtime=$(stat -f %m "$link")
        intended_mtime=$(stat -f %m "$script")
        if [[ "$current_mtime" -lt "$intended_mtime" ]]; then
          echo "Updating $link..."
          sudo rm "$link"
          sudo ln -s "$script" "$link"
        else
          echo -e "  Symlink already exists and points to the correct file."
        fi
      fi
    else
      sudo ln -s "$script" "$link"
    fi
  done

  for config in "${configFiles[@]}"; do
    if [ -n "$SPIN" ]; then
      if [[ $config == "keybindings" ]]; then
        echo "Installing $config..."
        source_file="$CODE_CONFIG_DIR/$config.json"
      fi
    fi
  done
}

setupDotfiles

if [[ ! "$SPIN" ]]; then
  exec zsh
fi
